/**
 * AudioFFmpeg.mm — ObjC++ bridge
 *
 * .mm extension = ObjC++ (can mix ObjC and C++).
 * Required because React Native Codegen emits C++ headers;
 * plain .m (ObjC) cannot include them.
 *
 * Responsibilities:
 *  1. Register the module with React Native (RCT_EXPORT_MODULE)
 *  2. Connect the JSI/Turbo bridge (getTurboModule)
 *  3. Forward every method call to AudioFFmpegImpl (Swift)
 *  4. Relay Swift events → JS via RCTEventEmitter
 */

#import "AudioFFmpeg.h"
#import "AudioFFmpegLame.h"

// React Native Turbo Module headers (kept here, not in .h, to avoid modular include errors)
#import <ReactCommon/RCTTurboModule.h>
#import <ReactCodegen/RNAudioFFmpegSpec/RNAudioFFmpegSpec.h>

// Auto-generated by Xcode from AudioFFmpegImpl.swift.
#import "AudioFFmpeg-Swift.h"

// Declare spec conformance in the .mm, not in the .h
@interface AudioFFmpeg () <NativeAudioFFmpegSpec>
@end

@implementation AudioFFmpeg {
    AudioFFmpegImpl *_impl;
}

// ─── Module registration ──────────────────────────────────────────────────────

// "NativeAudioFFmpeg" must exactly match TurboModuleRegistry.getEnforcing<Spec>('NativeAudioFFmpeg')
RCT_EXPORT_MODULE(NativeAudioFFmpeg)

- (instancetype)init {
    if (self = [super init]) {
        _impl = [[AudioFFmpegImpl alloc] init];

        // Wire Swift → ObjC++ → JS events.
        // IMPORTANT: FFmpegKit fires callbacks on its own background threads.
        // RCTEventEmitter.sendEventWithName:body: must be called from the
        // main queue — dispatch_async ensures thread safety.
        __weak __typeof__(self) weakSelf = self;
        _impl.onEvent = ^(NSString *name, NSDictionary *body) {
            dispatch_async(dispatch_get_main_queue(), ^{
                __strong __typeof__(weakSelf) strongSelf = weakSelf;
                if (!strongSelf) return;
                [strongSelf sendEventWithName:name body:body];
            });
        };

        _impl.encodeMp3 = ^BOOL(NSString *wavPath, NSString *mp3Path) {
            NSError *error = nil;
            return [AudioFFmpegLame encodeWavFile:wavPath toMp3File:mp3Path error:&error];
        };
    }
    return self;
}

// ─── JSI / Turbo Module bridge ────────────────────────────────────────────────

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
    return std::make_shared<facebook::react::NativeAudioFFmpegSpecJSI>(params);
}

// ─── NativeAudioFFmpegSpec protocol methods (New Architecture) ────────────────

- (void)execute:(NSString *)command
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject
{
    [_impl execute:command
           resolve:resolve
            reject:^(NSString *code, NSString *message) {
                reject(code, message, nil);
            }];
}

- (void)executeAsync:(NSString *)command
           sessionId:(NSString *)sessionId
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject
{
    [_impl executeAsync:command
              sessionId:sessionId
                resolve:^{ resolve(nil); }
                 reject:^(NSString *code, NSString *message) {
                     reject(code, message, nil);
                 }];
}

- (void)cancel:(NSString *)sessionId
       resolve:(RCTPromiseResolveBlock)resolve
        reject:(RCTPromiseRejectBlock)reject
{
    [_impl cancel:sessionId];
    resolve(nil);
}

- (NSString *)getVersion
{
    return [_impl getVersion];
}

// ─── RCTEventEmitter ─────────────────────────────────────────────────────────

- (NSArray<NSString *> *)supportedEvents {
    return @[
        @"AudioFFmpegLog",
        @"AudioFFmpegProgress",
        @"AudioFFmpegComplete"
    ];
}

// Required by RCTEventEmitter — called when the first JS listener is added.
// Must be overridden explicitly; without it some New Architecture plumbing
// doesn't properly set up the _eventEmitterCallback used by New Arch events.
- (void)startObserving {}

// Required by RCTEventEmitter — called when the last JS listener is removed.
- (void)stopObserving {}

+ (BOOL)requiresMainQueueSetup { return NO; }

@end
